### ISSUE TITLE
Compilation Errors when using Amazon SDK SPM

### ISSUE THREAD

**Issue by arehman86** [aws/amazon-chime-sdk-ios-spm#9] opened 2024-05-06 05:04 UTC
I have an objective-c project which I am working on right now. Previously I have downloaded xcframeworks and used it manually but now I have to use SPM. So I removed xcframeworks from the project and used SPM with video. When compiling the code I am getting compilation errors. I am importing the header like this `#import <AmazonChimeSDK/AmazonChimeSDK-Swift.h>` but getting compilation errors in this header.

![Screenshot 2024-05-06 at 10 02 21 AM](https://github.com/aws/amazon-chime-sdk-ios-spm/assets/62689814/b7bca13c-7620-42ef-a07d-6387c0279f6c)

**Comment by georgezy-amzn** [comment] 2024-05-22 23:53
Duplicate of https://github.com/aws/amazon-chime-sdk-ios/issues/672

**Closed by georgezy-amzn** 2024-05-22 23:53 UTC
